# Generated by Django 5.1.1 on 2025-12-22 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start"]},
        ),
        migrations.RemoveField(
            model_name="event",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="event",
            name="date_event",
        ),
        migrations.RemoveField(
            model_name="event",
            name="date_modified",
        ),
        migrations.RemoveField(
            model_name="event",
            name="name",
        ),
        migrations.AddField(
            model_name="event",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Couleur pour le calendrier (ex: red, #FF0000)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="end",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="is_urgent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="start",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="title",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name="CommerceEvent",
        ),
    ]
