# Generated by Django 5.1.1 on 2025-12-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_options_remove_event_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="bg_color",
            field=models.CharField(
                blank=True,
                help_text="Couleur de fond pour le calendrier (ex: red, #FF0000)",
                max_length=20,
            ),
        ),
    ]
