# Generated by Django 5.1.1 on 2025-12-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_bg_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="color",
        ),
    ]
