# Generated by Django 5.1.1 on 2025-12-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_event_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Couleur pour le calendrier (ex: red, #FF0000)",
                max_length=20,
            ),
        ),
    ]
