# Generated by Django 5.1.1 on 2025-12-23 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="bg_color",
        ),
        migrations.AddField(
            model_name="event",
            name="text_color",
            field=models.CharField(
                blank=True,
                help_text="Couleur pour le calendrier (ex: red, #FF0000)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Couleur de fond pour le calendrier (ex: red, #FF0000)",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#3788d8",
                        help_text="Couleur de fond (HEX ou nom CSS)",
                        max_length=20,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#ffffff", help_text="Couleur du texte", max_length=20
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "color", "text_color"),
                        name="unique_category_name",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_category",
                to="events.category",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_done", models.BooleanField(default=False)),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, help_text="Date limite de la tâche", null=True
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="1 = basse, 2 = normale, 3 = haute"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_event",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["is_done", "-priority", "due_date"],
            },
        ),
    ]
