# Generated by Django 5.1.1 on 2025-10-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fokotany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("secteur", models.CharField(max_length=200)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_modificated", models.DateField(auto_now=True)),
            ],
        ),
    ]
