# Generated by Django 5.1.1 on 2025-10-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fokotany",
            name="secteur",
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_modificated", models.DateField(auto_now=True)),
                (
                    "fokotany",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.fokotany",
                    ),
                ),
            ],
        ),
    ]
