# Generated by Django 5.1.1 on 2025-10-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_role_date_created_role_date_modificated"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="grade",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="grade",
            field=models.IntegerField(default=0),
        ),
    ]
