# Generated by Django 5.1.1 on 2025-10-30 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0003_role_grade_service_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="is_boss",
        ),
    ]
