# Generated by Django 5.1.1 on 2025-10-14 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0003_role_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="Common",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("district", models.CharField(max_length=80)),
                (
                    "boss",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="administration.staff",
                    ),
                ),
            ],
        ),
    ]
