# Generated by Django 5.1.1 on 2025-10-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0004_common"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="common",
            name="boss",
        ),
        migrations.RemoveField(
            model_name="service",
            name="boss",
        ),
        migrations.AddField(
            model_name="role",
            name="is_boss",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
