# Generated by Django 5.1.1 on 2025-10-16 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0005_remove_common_boss_remove_service_boss_role_is_boss"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="date_fired",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="date_joined",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="date_modificated",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_fired",
            field=models.BooleanField(default=False),
        ),
    ]
