# Generated by Django 5.1.1 on 2025-10-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0006_staff_date_fired_staff_date_joined_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="menu",
        ),
    ]
