# Generated by Django 5.1.1 on 2025-10-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0007_remove_application_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="is_boss",
            field=models.BooleanField(default=False),
        ),
    ]
