# Generated by Django 5.1.1 on 2025-10-16 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0008_alter_role_is_boss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="administration.service"
            ),
        ),
    ]
