# Generated by Django 5.1.1 on 2025-10-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0009_alter_role_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="conctact_1",
            new_name="contact_1",
        ),
        migrations.RenameField(
            model_name="staff",
            old_name="conctact_2",
            new_name="contact_2",
        ),
    ]
