# Generated by Django 5.1.1 on 2025-10-16 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0010_rename_conctact_1_staff_contact_1_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("name", "service"), name="unique_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "gender", "birthday"),
                name="unique_staff",
            ),
        ),
    ]
