# Generated by Django 5.1.1 on 2025-10-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0011_role_unique_role_staff_unique_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
