# Generated by Django 5.1.1 on 2025-10-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0012_staff_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="staff",
        ),
        migrations.AddField(
            model_name="staff",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="administration.role",
            ),
        ),
    ]
