"""
Django settings for CommonAdmin project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

import os
import environ

ENV = environ.Env()
ENV.read_env(os.path.join(BASE_DIR, '.env'))
CHECKED_ENV = ENV('PROJECT_ENV') == 'common'

COMMON_NAME = "Betsiaka"

# CREATED SERVICES
SERVICES_APP = [
    {"name": "dashboard", "title": "accueil".title(), "url": "dashboard:index"},
    {"name": "civil", "title": "état civil".title(), "url": "civil:index"},
    {"name": "events", "title": "événements".title(), "url": "events:index"},
    {"name": "finances", "title": "trésorerie".title(), "url": "finances:index"},
    {"name": "mines", "title": "mines".title(), "url": "mines:index"},
    {"name": "social", "title": "affaires sociales".title(), "url": "social:index"},
    {"name": "administration", "title": "administration".title(), "url": "administration:index"},
]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ENV('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = CHECKED_ENV

ALLOWED_HOSTS = ['*'] if CHECKED_ENV else []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # Applications
    "account.apps.AccountConfig",
    *[service['name'] for service in SERVICES_APP],
    # "dashboard.apps.DashboardConfig",
    # "civil.apps.CivilConfig",
    "theme.apps.ThemeConfig",
    # Tools
    "django_browser_reload",
    "django_filters",
    "tailwind"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = "CommonAdmin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "theme.context_processors.theme", # Customed Context Processors
            ],
        },
    },
]

WSGI_APPLICATION = "CommonAdmin.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.mysql",
    #     "NAME": env("DB_NAME"),
    #     "USER": env("DB_USER"),
    #     "PASSWORD": env("DB_PASS"),
    #     "HOST": "127.0.0.1",
    #     "PORT": "3306",
    #     "OPTION": {
    #         "slq_mode": "STRICT_TRANS_TABLES, NO_ENGINE_SUBSTITUTION"
    #     }
    # },
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "OPTIONS": {
            "read_default_file": "my.cnf",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Customed Settings
TAILWIND_APP_NAME = "theme"

INTERNAL_IPS = [
    "127.0.0.1",
    ]

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = 'assets'
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"

AUTH_USER_MODEL = "account.user"