"""
Django settings for CommonAdmin project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

import os
import environ
from django.utils.translation import gettext_noop as _

ENV = environ.Env()
ENV.read_env(os.path.join(BASE_DIR, '.env'))
CHECKED_ENV = ENV('PROJECT_ENV') == 'common'

COMMON_NAME = "Betsiaka"

# CREATED SERVICES
MENU_SERVICES = {
    "dashboard": [
            {"name": "dashboard", "title": _("dashboard"), "url": "dashboard:index"},
        ],
    "civil": [
            {"name": "dashboard", "title": _("dashboard"), "url": "civil:index"}, 
            {"name": "birth", "title": _("birth certificate"), "url": "civil:birth"},
            {"name": "death", "title": _("death certificate"), "url": "civil:death"},
            {"name": "marriage", "title": _("marriage certificate"), "url": "civil:marriage"},
        ],
    "events": [
            {"name": "dashboard", "title": _("dashboard"), "url": "events:index"}, 
        ],
    "finances": [
            {"name": "dashboard", "title": _("dashboard"), "url": "finances:index"}, 
        ],
    "mines": [
            {"name": "dashboard", "title": _("dashboard"), "url": "mines:index"}, 
        ],
    "social": [
            {"name": "dashboard", "title": _("dashboard"), "url": "social:index"}, 
        ],
    "administration": [
            {"name": "dashboard", "title": _("dashboard"), "url": "administration:index"},  
            {"name": "staff", "title": _("staff"), "url": "administration:staff"},
            {"name": "user", "title": _("user"), "url": "administration:user"},
            {"name": "role", "title": _("role"), "url": "administration:role"},
            {"name": "settings", "title": _("settings"), "url": "administration:settings"},
        ]
}
SERVICES_APP = [
    {"name": "dashboard", "title": _("home"), "url": "dashboard:index", "icon1": "..\static\icons\house-blank_9243280.svg", "icon2": "..\static\icons\house-blank_9243857.svg",  "submenus": [
        {"name": "dashboard", "title": _("dashboard"), "url": "dashboard:index"},
        ]},
    {"name": "civil", "title": _("civil status"), "url": "civil:index", "icon1": "", "icon2": "", "submenus": [
        {"name": "dashboard", "title": _("dashboard"), "url": "civil:index"}, 
        {"name": "birth", "title": _("birth certificate"), "url": "civil:birth"},
        {"name": "death", "title": _("death certificate"), "url": "civil:death"},
        {"name": "marriage", "title": _("marriage certificate"), "url": "civil:marriage"},
        ]},
    {"name": "events", "title": _("events"), "url": "events:index", "icon1": "", "icon2": "", "submenus": [
        {"name": "dashboard", "title": _("dashboard"), "url": "events:index"}, 
        ]},
    {"name": "finances", "title": _("finances"), "url": "finances:index", "icon1": "", "icon2": "", "submenus": [
        {"name": "dashboard", "title": _("dashboard"), "url": "finances:index"}, 
        {"name": "", "title": "", "url": ""}
        ]},
    {"name": "mines", "title": _("mines"), "url": "mines:index", "icon1": "", "icon2": "", "submenus": [
        {"name": "dashboard", "title": _("dashboard"), "url": "mines:index"}, 
        {"name": "", "title": "", "url": ""}
        ]},
    {"name": "social", "title": _("social business"), "url": "social:index", "icon1": "", "icon2": "", "submenus": [
        {"name": "dashboard", "title": _("dashboard"), "url": "social:index"}, 
        {"name": "", "title": "", "url": ""}
        ]},
    {"name": "administration", "title": _("administration"), "url": "administration:index", "icon1": "", "icon2": "", "submenus": [
        {"name": "dashboard", "title": _("dashboard"), "url": "administration:index"},  
        {"name": "staff", "title": _("staff"), "url": "administration:staff"},
        {"name": "user", "title": _("user"), "url": "administration:user"},
        {"name": "role", "title": _("role"), "url": "administration:role"},
        {"name": "settings", "title": _("settings"), "url": "administration:settings"},
        ]},
]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ENV('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = CHECKED_ENV

ALLOWED_HOSTS = ['*'] if CHECKED_ENV else []

# Application definition

INSTALLED_APPS = [
    # Applications par défaut
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # Fonctions template personnalisées
    "civil.templatetags.isa_gasy",
    "civil.templatetags.iterator",
    "civil.templatetags.text_format",
    "civil.templatetags.date_filter",
    # Applications
    "account.apps.AccountConfig",
    *[service['name'] for service in SERVICES_APP],
    # "dashboard.apps.DashboardConfig",
    # "civil.apps.CivilConfig",
    "theme.apps.ThemeConfig",
    # Tools
    # "django_browser_reload",
    "django_filters",
    "tailwind"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware", # Ajout du middleware de traduction
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = "CommonAdmin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "theme.context_processors.theme", # Customed Context Processors
            ],
        },
    },
]

WSGI_APPLICATION = "CommonAdmin.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.mysql",
    #     "NAME": env("DB_NAME"),
    #     "USER": env("DB_USER"),
    #     "PASSWORD": env("DB_PASS"),
    #     "HOST": "127.0.0.1",
    #     "PORT": "3306",
    #     "OPTION": {
    #         "slq_mode": "STRICT_TRANS_TABLES, NO_ENGINE_SUBSTITUTION"
    #     }
    # },
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "OPTIONS": {
            "read_default_file": "my.cnf",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "Indian/Antananarivo" # ou Etc/GMT-3

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Configuration des langues disponibles
LANGUAGES = [
    ('fr', 'Français'),
    ('mg', 'Malagasy'),
    ('en', 'English'),
]

# Dossier contenant les fichiers de traduction
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Configuration de la session pour stocker la langue
LANGUAGE_COOKIE_NAME = 'django_language'

# Configuration des sessions
SESSION_COOKIE_AGE = 86400  # Session valide pendant 24 heures (1 jour)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session expire à la fermeture du navigateur
SESSION_COOKIE_SECURE = False  # En développement, on accepte HTTP
SESSION_COOKIE_HTTPONLY = True  # Empêche l'accès aux cookies via JavaScript
SESSION_SAVE_EVERY_REQUEST = True  # Met à jour l'expiration de la session à chaque requête

# En production, activez ces paramètres :
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'assets'  # Chemin absolu pour STATIC_ROOT
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Utilisation de Path pour cohérence

# Ajout de whitenoise pour servir les fichiers statiques en production
if not DEBUG:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Customed Settings
TAILWIND_APP_NAME = "theme"

INTERNAL_IPS = [
    "127.0.0.1", 
    ]

NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"

AUTH_USER_MODEL = "account.user"

CSRF_TRUSTED_ORIGINS = [
    "https://96956fdc2d35.ngrok-free.app",
]