# Generated by Django 5.1.1 on 2025-11-06 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthCertificateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("person_last_name", models.CharField(max_length=100)),
                ("person_first_name", models.CharField(max_length=100, null=True)),
                ("person_birth_place", models.CharField(max_length=100)),
                ("person_birthday", models.DateTimeField()),
                ("person_address", models.CharField(max_length=100, null=True)),
                ("father_last_name", models.CharField(max_length=100, null=True)),
                ("father_first_name", models.CharField(max_length=100, null=True)),
                ("father_birth_place", models.CharField(max_length=100, null=True)),
                ("father_birthday", models.DateTimeField(null=True)),
                ("father_carreer", models.CharField(max_length=80, null=True)),
                ("father_address", models.CharField(max_length=100, null=True)),
                ("mother_last_name", models.CharField(max_length=100)),
                ("mother_first_name", models.CharField(max_length=100)),
                ("mother_birth_place", models.CharField(max_length=100)),
                ("mother_birthday", models.DateTimeField()),
                ("mother_carreer", models.CharField(max_length=80)),
                ("mother_address", models.CharField(max_length=100)),
                ("declarer_last_name", models.CharField(max_length=100)),
                ("declarer_first_name", models.CharField(max_length=100, null=True)),
                ("declarer_birth_place", models.CharField(max_length=100)),
                ("declarer_birthday", models.DateTimeField()),
                ("declarer_carreer", models.CharField(max_length=80)),
                ("declarer_address", models.CharField(max_length=100)),
                ("was_alive", models.BooleanField(default=True)),
                ("date_register", models.DateTimeField(null=True)),
                ("date_recognization", models.DateTimeField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("client_detail", models.CharField(max_length=120, null=True)),
                ("date_validated", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Draft"),
                            ("V", "Validated"),
                            ("C", "Cancelled"),
                        ],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("notes", models.TextField(null=True)),
                ("price", models.FloatField(default=1000)),
                ("num_copy", models.IntegerField(default=1)),
                (
                    "fokotany",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="deathdoc_fokotany",
                        to="administration.fokotany",
                    ),
                ),
                (
                    "responsible_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="deathdoc_responsible_staff",
                        to="administration.staff",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="document_birth_staff",
                        to="administration.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeathCertificateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_last_name", models.CharField(max_length=100)),
                ("person_first_name", models.CharField(max_length=100, null=True)),
                ("person_birth_place", models.CharField(max_length=100)),
                ("person_birthday", models.DateTimeField()),
                ("person_carreer", models.CharField(max_length=80, null=True)),
                ("person_address", models.CharField(max_length=100, null=True)),
                ("father_last_name", models.CharField(max_length=100, null=True)),
                ("father_first_name", models.CharField(max_length=100, null=True)),
                ("father_birth_place", models.CharField(max_length=100, null=True)),
                ("father_birthday", models.DateTimeField(null=True)),
                ("father_carreer", models.CharField(max_length=80, null=True)),
                ("father_address", models.CharField(max_length=100, null=True)),
                ("mother_last_name", models.CharField(max_length=100, null=True)),
                ("mother_first_name", models.CharField(max_length=100, null=True)),
                ("mother_birth_place", models.CharField(max_length=100, null=True)),
                ("mother_birthday", models.DateTimeField(null=True)),
                ("mother_carreer", models.CharField(max_length=80, null=True)),
                ("mother_address", models.CharField(max_length=100, null=True)),
                ("declarer_last_name", models.CharField(max_length=100)),
                ("declarer_first_name", models.CharField(max_length=100, null=True)),
                ("declarer_birth_place", models.CharField(max_length=100)),
                ("declarer_birthday", models.DateTimeField()),
                ("declarer_carreer", models.CharField(max_length=80)),
                ("declarer_address", models.CharField(max_length=100)),
                ("declarer_relationship", models.CharField(max_length=80)),
                ("declarer_was_present", models.BooleanField()),
                ("date_register", models.DateTimeField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("client_detail", models.CharField(max_length=120, null=True)),
                ("date_validated", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Draft"),
                            ("V", "Validated"),
                            ("C", "Cancelled"),
                        ],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("notes", models.TextField(null=True)),
                ("price", models.FloatField(default=1000)),
                ("num_copy", models.IntegerField(default=1)),
                (
                    "fokotany",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="birthdoc_fokotany",
                        to="administration.fokotany",
                    ),
                ),
                (
                    "responsible_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="birthdoc_responsible_staff",
                        to="administration.staff",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="document_death_staff",
                        to="administration.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("birth_place", models.CharField(max_length=100, null=True)),
                ("birthday", models.DateTimeField(null=True)),
                ("carreer", models.CharField(max_length=80, null=True)),
                ("address", models.CharField(max_length=100, null=True)),
                ("is_alive", models.BooleanField(default=True)),
                ("is_married", models.BooleanField(default=False)),
                ("is_parent", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("first_name", "last_name", "gender", "birthday"),
                        name="person_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MarriageCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wedding_day", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("date_register", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "fokotany",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="marriage_fokotany",
                        to="administration.fokotany",
                    ),
                ),
                (
                    "responsible_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="marriage_responsible_staff",
                        to="administration.staff",
                    ),
                ),
                (
                    "bride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="marriage_wife",
                        to="civil.person",
                    ),
                ),
                (
                    "groom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="marriage_husband",
                        to="civil.person",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("groom", "bride", "wedding_day"),
                        name="unique_marriage_certificate",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeathCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("declarer_relationship", models.CharField(max_length=80)),
                ("declarer_was_present", models.BooleanField()),
                ("death_day", models.DateTimeField()),
                ("death_place", models.CharField(max_length=100)),
                ("date_register", models.DateTimeField(null=True)),
                ("date_declaration", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "fokotany",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="death_fokotany",
                        to="administration.fokotany",
                    ),
                ),
                (
                    "responsible_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="death_responsible_staff",
                        to="administration.staff",
                    ),
                ),
                (
                    "declarer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="death_declarer",
                        to="civil.person",
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="death_father",
                        to="civil.person",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="death_mother",
                        to="civil.person",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="death_person",
                        to="civil.person",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "declarer", "responsible_staff", "fokotany"),
                        name="unique_death_certificate",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BirthCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("declarer_relationship", models.CharField(max_length=80)),
                ("declarer_was_present", models.BooleanField()),
                (
                    "responsible_staff_name",
                    models.CharField(
                        default="TEXNAS Marie Edonisse Henri", max_length=100
                    ),
                ),
                (
                    "responsible_staff_role",
                    models.CharField(default="Ben'ny Tanàna", max_length=100),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[("N", "Birth"), ("R", "Birth and Recognition")],
                        max_length=1,
                    ),
                ),
                ("was_alive", models.BooleanField(default=True)),
                ("date_declaration", models.DateTimeField()),
                ("date_register", models.DateTimeField(null=True)),
                ("date_recognization", models.DateTimeField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "fokotany",
                    models.ForeignKey(
                        default=3,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="birth_fokotany",
                        to="administration.fokotany",
                    ),
                ),
                (
                    "responsible_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="birth_responsible_staff",
                        to="administration.staff",
                    ),
                ),
                (
                    "declarer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="birth_declarer",
                        to="civil.person",
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="birth_father",
                        to="civil.person",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="birth_mother",
                        to="civil.person",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birth_person",
                        to="civil.person",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "father", "mother", "declarer"),
                        name="unique_birth_certificate",
                    )
                ],
            },
        ),
    ]
