# Generated by Django 5.1.1 on 2025-10-14 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("father_carreer", models.CharField(max_length=80, null=True)),
                ("mother_carreer", models.CharField(max_length=80)),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("F", "Fatherless"),
                            ("N", "Normal"),
                            ("R", "Recognition"),
                        ],
                        max_length=1,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "fokotany",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="birth_fokotany",
                        to="administration.fokotany",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("VALIDATED", "Validated"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("validated_by", models.CharField(blank=True, max_length=200)),
                (
                    "signature",
                    models.TextField(
                        blank=True, help_text="Digital signature or stamp info"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "birth_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="civil.birthcertificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Document",
                "verbose_name_plural": "Certificate Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("birth_place", models.CharField(max_length=100)),
                ("birthday", models.DateTimeField()),
                ("is_parent", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("first_name", "last_name", "gender", "birthday"),
                        name="person_unique",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="born",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="birth_born",
                to="civil.person",
            ),
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="declarer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="birth_declarer",
                to="civil.person",
            ),
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="father",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="birth_father",
                to="civil.person",
            ),
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="mother",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="birth_mother",
                to="civil.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="birthcertificate",
            constraint=models.UniqueConstraint(
                fields=("born", "father", "mother", "declarer"),
                name="unique_birth_certificate",
            ),
        ),
    ]
