# Generated by Django 5.1.1 on 2025-10-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathcertificate",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
