# Generated by Django 5.1.1 on 2025-10-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificate",
            name="father_address",
            field=models.CharField(default="No address", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="father_carreer",
            field=models.CharField(default="No carreer", max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="mother_address",
            field=models.CharField(default="No address", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="mother_carreer",
            field=models.CharField(default="No carreer", max_length=80),
            preserve_default=False,
        ),
    ]
