# Generated by Django 5.1.1 on 2025-11-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="birthcertificate",
            name="responsible_staff",
        ),
    ]
