# Generated by Django 5.1.1 on 2025-11-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
        ("civil", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recognizationcertificate",
            constraint=models.UniqueConstraint(
                fields=("person", "recognized_by", "date_modified"),
                name="unique_recognization_certificate",
            ),
        ),
    ]
