# Generated by Django 5.1.1 on 2025-10-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificate",
            name="declarer_carreer",
            field=models.CharField(default="Unknown", max_length=80),
            preserve_default=False,
        ),
    ]
