# Generated by Django 5.1.1 on 2025-11-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0002_remove_birthcertificate_responsible_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificate",
            name="responsible_staff_name",
            field=models.CharField(max_length=100),
        ),
    ]
