# Generated by Django 5.1.1 on 2025-10-14 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0004_common"),
        ("civil", "0002_birthcertificate_declarer_carreer"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificate",
            name="staff_responsible",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="birth_reponsible",
                to="administration.staff",
            ),
        ),
    ]
