# Generated by Django 5.1.1 on 2025-10-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0002_deathcertificate_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deathcertificate",
            name="number",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
