# Generated by Django 5.1.1 on 2025-10-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0002_birthcertificate_father_address_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "birthday"), name="person_unique"
            ),
        ),
    ]
