# Generated by Django 5.1.1 on 2025-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
        ("civil", "0002_recognizationcertificate_unique_recognization_certificate"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recognizationcertificate",
            name="unique_recognization_certificate",
        ),
        migrations.AddConstraint(
            model_name="recognizationcertificate",
            constraint=models.UniqueConstraint(
                fields=("person", "recognized_by"),
                name="unique_recognization_certificate",
            ),
        ),
    ]
