# Generated by Django 5.1.1 on 2025-10-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0003_birthcertificate_staff_responsible"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificate",
            name="declarer_address",
            field=models.CharField(default="Betsiaka", max_length=100),
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="father_address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="mother_address",
            field=models.CharField(default="Betsiaka", max_length=100),
        ),
    ]
