# Generated by Django 5.1.1 on 2025-10-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0003_person_person_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificate",
            name="father_address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="birthcertificate",
            name="father_carreer",
            field=models.CharField(max_length=80, null=True),
        ),
    ]
