# Generated by Django 5.1.1 on 2025-11-01 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0003_alter_deathcertificate_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeathCertificateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("father_carreer", models.CharField(max_length=80, null=True)),
                ("father_address", models.CharField(max_length=100, null=True)),
                ("mother_carreer", models.CharField(max_length=80, null=True)),
                ("mother_address", models.CharField(max_length=100, null=True)),
                ("declarer_carreer", models.CharField(max_length=80)),
                ("declarer_address", models.CharField(max_length=100)),
                ("was_born", models.BooleanField(default=True)),
                ("date_register", models.DateTimeField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("date_validated", models.DateTimeField(blank=True, null=True)),
                ("document_number", models.IntegerField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Draft"),
                            ("V", "Validated"),
                            ("C", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("price", models.FloatField(default=1000)),
                ("num_copy", models.IntegerField(default=1)),
                (
                    "death_certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_death",
                        to="civil.deathcertificate",
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_death_father",
                        to="civil.person",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_death_mother",
                        to="civil.person",
                    ),
                ),
            ],
        ),
    ]
