# Generated by Django 5.1.1 on 2025-11-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0003_alter_birthcertificate_responsible_staff_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="person",
            name="carreer",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
