# Generated by Django 5.1.1 on 2025-11-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "civil",
            "0003_remove_recognizationcertificate_unique_recognization_certificate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="person_is_alive",
            field=models.BooleanField(default=True),
        ),
    ]
