# Generated by Django 5.1.1 on 2025-10-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_remove_fokotany_secteur_sector"),
        ("civil", "0004_alter_birthcertificate_father_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="birthcertificate",
            name="father_address",
        ),
        migrations.RemoveField(
            model_name="birthcertificate",
            name="mother_address",
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="birthcertificate",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name="birthcertificate",
            constraint=models.UniqueConstraint(
                fields=("born", "father", "mother"), name="unique_birth_certificate"
            ),
        ),
    ]
