# Generated by Django 5.1.1 on 2025-10-16 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0005_remove_common_boss_remove_service_boss_role_is_boss"),
        ("civil", "0004_birthcertificate_declarer_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificate",
            name="staff_responsible",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="birth_reponsible",
                to="administration.role",
            ),
        ),
    ]
