# Generated by Django 5.1.1 on 2025-11-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0004_alter_person_address_alter_person_carreer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="birthday",
            field=models.DateTimeField(blank=True),
        ),
    ]
