# Generated by Django 5.1.1 on 2025-11-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0004_birthcertificatedocument_person_is_alive"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="birthcertificatedocument",
            name="date_recognization",
        ),
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="is_recognized",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
