# Generated by Django 5.1.1 on 2025-11-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0004_deathcertificatedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathcertificate",
            name="was_born",
            field=models.BooleanField(default=True),
        ),
    ]
