# Generated by Django 5.1.1 on 2025-11-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0005_remove_birthcertificatedocument_date_recognization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="date_recognization",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="recognization_numero",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="is_recognized",
            field=models.BooleanField(default=False),
        ),
    ]
