# Generated by Django 5.1.1 on 2025-11-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0005_deathcertificate_was_born"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="date_modified",
        ),
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="date_register",
        ),
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="date_validated",
        ),
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="declarer_address",
        ),
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="declarer_carreer",
        ),
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="document_number",
        ),
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="father",
        ),
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="father_address",
        ),
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="father_carreer",
        ),
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="mother",
        ),
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="mother_address",
        ),
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="mother_carreer",
        ),
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="was_born",
        ),
    ]
