# Generated by Django 5.1.1 on 2025-10-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0005_alter_birthcertificate_staff_responsible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="birthcertificate",
            name="staff_responsible",
        ),
    ]
