# Generated by Django 5.1.1 on 2025-11-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0005_alter_person_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="birth_place",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
