# Generated by Django 5.1.1 on 2025-10-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0005_remove_birthcertificate_father_address_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="person",
            name="person_unique",
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "gender", "birthday"),
                name="person_unique",
            ),
        ),
    ]
