# Generated by Django 5.1.1 on 2025-11-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0006_remove_deathcertificatedocument_date_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="birthcertificatedocument",
            old_name="birth_certificate",
            new_name="certificate",
        ),
        migrations.RenameField(
            model_name="deathcertificatedocument",
            old_name="death_certificate",
            new_name="certificate",
        ),
    ]
