# Generated by Django 5.1.1 on 2025-11-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0006_alter_person_birth_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="birthcertificate",
            name="certificate_type",
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="had_father",
            field=models.BooleanField(default=True),
        ),
    ]
