# Generated by Django 5.1.1 on 2025-10-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0006_remove_birthcertificate_staff_responsible"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_alive",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="birthcertificate",
            name="certificate_type",
            field=models.CharField(
                choices=[
                    ("F", "Fatherless Birth"),
                    ("N", "Normal Birth"),
                    ("R", "Birth and Recognition"),
                ],
                max_length=1,
            ),
        ),
    ]
