# Generated by Django 5.1.1 on 2025-10-10 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0006_remove_person_person_unique_person_person_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("VALIDATED", "Validated"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("validated_by", models.CharField(blank=True, max_length=200)),
                (
                    "signature",
                    models.TextField(
                        blank=True, help_text="Digital signature or stamp info"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "birth_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="civil.birthcertificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Document",
                "verbose_name_plural": "Certificate Documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
