# Generated by Django 5.1.1 on 2025-11-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0006_birthcertificatedocument_date_recognization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="recognized_by_first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="recognized_by_last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
