# Generated by Django 5.1.1 on 2025-11-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0007_remove_birthcertificate_certificate_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="birth_place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="carreer",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
