# Generated by Django 5.1.1 on 2025-11-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "civil",
            "0007_rename_birth_certificate_birthcertificatedocument_certificate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="client_detail",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="client_detail",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
