# Generated by Django 5.1.1 on 2025-10-13 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0007_certificatedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificate",
            name="declarer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="birth_declarer",
                to="civil.person",
            ),
        ),
        migrations.AlterField(
            model_name="birthcertificate",
            name="born",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="birth_born",
                to="civil.person",
            ),
        ),
        migrations.AlterField(
            model_name="birthcertificate",
            name="father",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="birth_father",
                to="civil.person",
            ),
        ),
        migrations.AlterField(
            model_name="birthcertificate",
            name="mother",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="birth_mother",
                to="civil.person",
            ),
        ),
    ]
