# Generated by Django 5.1.1 on 2025-11-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0007_birthcertificatedocument_recognized_by_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marriagecertificate",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
