# Generated by Django 5.1.1 on 2025-10-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0007_person_is_alive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="is_alive",
            field=models.BooleanField(default=False),
        ),
    ]
