# Generated by Django 5.1.1 on 2025-10-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0008_alter_person_is_alive"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificate",
            name="was_alive",
            field=models.BooleanField(default=True),
        ),
    ]
