# Generated by Django 5.1.1 on 2025-10-13 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0008_birthcertificate_declarer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificate",
            name="declarer",
            field=models.ForeignKey(
                default=19,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="birth_declarer",
                to="civil.person",
            ),
        ),
    ]
