# Generated by Django 5.1.1 on 2025-11-19 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0008_marriagecertificate_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="marriagecertificate",
            name="date_declaration",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
