# Generated by Django 5.1.1 on 2025-11-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0008_birthcertificatedocument_client_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="notes",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="notes",
            field=models.TextField(null=True),
        ),
    ]
