# Generated by Django 5.1.1 on 2025-11-06 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0008_alter_person_address_alter_person_birth_place_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="certificate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="birthdoc_certificate",
                to="civil.birthcertificate",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="certificate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deathdoc_certificate",
                to="civil.birthcertificate",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
