# Generated by Django 5.1.1 on 2025-11-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0009_birthcertificatedocument_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="certificate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="birthdoc_certificate",
                to="civil.birthcertificate",
            ),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="certificate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deathdoc_certificate",
                to="civil.birthcertificate",
            ),
        ),
    ]
