# Generated by Django 5.1.1 on 2025-10-13 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_remove_fokotany_secteur_sector"),
        ("civil", "0009_alter_birthcertificate_declarer"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="birthcertificate",
            name="unique_birth_certificate",
        ),
        migrations.AlterField(
            model_name="birthcertificate",
            name="declarer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="birth_declarer",
                to="civil.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="birthcertificate",
            constraint=models.UniqueConstraint(
                fields=("born", "father", "mother", "declarer"),
                name="unique_birth_certificate",
            ),
        ),
    ]
