# Generated by Django 5.1.1 on 2025-11-19 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0009_marriagecertificate_date_declaration"),
    ]

    operations = [
        migrations.AddField(
            model_name="marriagecertificate",
            name="father_bride",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marriage_bride_father",
                to="civil.person",
            ),
        ),
        migrations.AddField(
            model_name="marriagecertificate",
            name="father_groom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marriage_groom_father",
                to="civil.person",
            ),
        ),
        migrations.AddField(
            model_name="marriagecertificate",
            name="mother_bride",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marriage_bride_mother",
                to="civil.person",
            ),
        ),
        migrations.AddField(
            model_name="marriagecertificate",
            name="mother_groom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marriage_groom_mother",
                to="civil.person",
            ),
        ),
        migrations.AddField(
            model_name="marriagecertificate",
            name="witness_bride",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marriage_witness_bride",
                to="civil.person",
            ),
        ),
        migrations.AddField(
            model_name="marriagecertificate",
            name="witness_groom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marriage_witness_groom",
                to="civil.person",
            ),
        ),
    ]
