# Generated by Django 5.1.1 on 2025-11-03 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0004_remove_role_is_boss"),
        ("civil", "0009_alter_birthcertificatedocument_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="validated_by",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="document_birth_staff",
                to="administration.staff",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="date_validated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="validated_by",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="document_death_staff",
                to="administration.staff",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="status",
            field=models.CharField(
                choices=[("D", "Draft"), ("V", "Validated"), ("C", "Cancelled")],
                default="D",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="status",
            field=models.CharField(
                choices=[("D", "Draft"), ("V", "Validated"), ("C", "Cancelled")],
                default="D",
                max_length=1,
            ),
        ),
    ]
