# Generated by Django 5.1.1 on 2025-10-21 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0011_role_unique_role_staff_unique_staff"),
        ("civil", "0009_birthcertificate_was_alive"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificate",
            name="date_recognization",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="responsible_role",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="birth_responsible_role",
                to="administration.role",
            ),
            preserve_default=False,
        ),
    ]
