# Generated by Django 5.1.1 on 2025-11-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0010_birthcertificatedocument_validated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_married",
            field=models.BooleanField(default=False),
        ),
    ]
