# Generated by Django 5.1.1 on 2025-10-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0013_remove_role_staff_staff_role"),
        ("civil", "0010_birthcertificate_date_recognization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="birthcertificate",
            name="responsible_role",
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="responsible_staff",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="birth_responsible_role",
                to="administration.staff",
            ),
            preserve_default=False,
        ),
    ]
