# Generated by Django 5.1.1 on 2025-11-19 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
        ("civil", "0010_marriagecertificate_father_bride_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarriageCertificateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("groom_last_name", models.CharField(max_length=100)),
                (
                    "groom_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("groom_birth_place", models.CharField(max_length=100)),
                ("groom_birthday", models.DateTimeField()),
                (
                    "groom_carreer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "groom_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bride_last_name", models.CharField(max_length=100)),
                (
                    "bride_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bride_birth_place", models.CharField(max_length=100)),
                ("bride_birthday", models.DateTimeField()),
                (
                    "bride_carreer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bride_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_groom_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_groom_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_groom_birth_place",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("father_groom_birthday", models.DateTimeField(null=True)),
                (
                    "father_groom_carreer",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "father_groom_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("father_groom_is_alive", models.BooleanField(default=True)),
                ("mother_groom_last_name", models.CharField(max_length=100)),
                (
                    "mother_groom_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mother_groom_birth_place", models.CharField(max_length=100)),
                ("mother_groom_birthday", models.DateTimeField()),
                ("mother_groom_carreer", models.CharField(max_length=80)),
                ("mother_groom_address", models.CharField(max_length=100)),
                ("mother_groom_is_alive", models.BooleanField(default=True)),
                (
                    "father_bride_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_bride_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_bride_birth_place",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("father_bride_birthday", models.DateTimeField(null=True)),
                (
                    "father_bride_carreer",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "father_bride_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("father_bride_is_alive", models.BooleanField(default=True)),
                ("mother_bride_last_name", models.CharField(max_length=100)),
                (
                    "mother_bride_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mother_bride_birth_place", models.CharField(max_length=100)),
                ("mother_bride_birthday", models.DateTimeField()),
                ("mother_bride_carreer", models.CharField(max_length=80)),
                ("mother_bride_address", models.CharField(max_length=100)),
                ("mother_bride_is_alive", models.BooleanField(default=True)),
                ("witness_groom_last_name", models.CharField(max_length=100)),
                (
                    "witness_groom_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "witness_groom_gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("witness_groom_birth_place", models.CharField(max_length=100)),
                ("witness_groom_birthday", models.DateTimeField()),
                ("witness_groom_carreer", models.CharField(max_length=80)),
                ("witness_groom_address", models.CharField(max_length=100)),
                ("witness_bride_last_name", models.CharField(max_length=100)),
                (
                    "witness_bride_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "witness_bride_gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("witness_bride_birth_place", models.CharField(max_length=100)),
                ("witness_bride_birthday", models.DateTimeField()),
                ("witness_bride_carreer", models.CharField(max_length=80)),
                ("witness_bride_address", models.CharField(max_length=100)),
                ("is_recognized", models.BooleanField(default=False)),
                ("wedding_day", models.DateTimeField()),
                ("responsible_staff_name", models.CharField(max_length=100)),
                (
                    "responsible_staff_role",
                    models.CharField(default="Ben'ny Tanàna", max_length=100),
                ),
                ("date_register", models.DateTimeField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("date_validated", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Draft"),
                            ("V", "Validated"),
                            ("C", "Cancelled"),
                        ],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("notes", models.TextField(null=True)),
                ("price", models.FloatField(default=1000)),
                ("num_copy", models.IntegerField(default=1)),
                (
                    "certificate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marriagedoc_certificate",
                        to="civil.marriagecertificate",
                    ),
                ),
                (
                    "fokotany",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="marriagedoc_fokotany",
                        to="administration.fokotany",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="document_marriage_staff",
                        to="administration.staff",
                    ),
                ),
            ],
        ),
    ]
