# Generated by Django 5.1.1 on 2025-11-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0010_alter_birthcertificatedocument_certificate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="client_detail",
        ),
    ]
