# Generated by Django 5.1.1 on 2025-11-20 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0011_marriagecertificatedocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marriagecertificate",
            name="witness_bride",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="marriage_witness_bride",
                to="civil.person",
            ),
        ),
        migrations.AlterField(
            model_name="marriagecertificate",
            name="witness_groom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="marriage_witness_groom",
                to="civil.person",
            ),
        ),
    ]
