# Generated by Django 5.1.1 on 2025-10-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0011_remove_birthcertificate_responsible_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatedocument",
            name="price",
            field=models.FloatField(default=1000),
        ),
    ]
