# Generated by Django 5.1.1 on 2025-11-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0004_remove_role_is_boss"),
        ("civil", "0012_alter_deathcertificatedocument_validated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="validated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="document_birth_staff",
                to="administration.staff",
            ),
        ),
    ]
