# Generated by Django 5.1.1 on 2025-11-06 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
        ("civil", "0012_remove_birthcertificate_responsible_staff_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="responsible_staff",
        ),
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="responsible_staff_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="responsible_staff_role",
            field=models.CharField(default="Ben'ny Tanàna", max_length=100),
        ),
        migrations.AlterField(
            model_name="birthcertificate",
            name="responsible_staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="birth_responsible_staff",
                to="administration.staff",
            ),
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="fokotany",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="birthdoc_fokotany",
                to="administration.fokotany",
            ),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="fokotany",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="deathdoc_fokotany",
                to="administration.fokotany",
            ),
        ),
    ]
