# Generated by Django 5.1.1 on 2025-10-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0012_certificatedocument_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatedocument",
            name="document_number",
            field=models.CharField(max_length=50),
        ),
    ]
