# Generated by Django 5.1.1 on 2025-11-20 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0012_alter_marriagecertificate_witness_bride_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marriagecertificatedocument",
            name="is_recognized",
        ),
    ]
