# Generated by Django 5.1.1 on 2025-11-03 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0013_alter_birthcertificatedocument_validated_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="client_detail",
        ),
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_alive",
            field=models.BooleanField(default=True),
        ),
    ]
