# Generated by Django 5.1.1 on 2025-10-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0013_alter_certificatedocument_document_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatedocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("F", "Fatherless Birth"),
                    ("N", "Normal Birth"),
                    ("R", "Birth and Recognition"),
                ],
                default="N",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
