# Generated by Django 5.1.1 on 2025-11-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0013_remove_deathcertificatedocument_responsible_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="declarer_relationship",
            field=models.CharField(default="rain-jaza", max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="declarer_was_present",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="had_father",
            field=models.BooleanField(default=True),
        ),
    ]
