# Generated by Django 5.1.1 on 2025-11-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0013_remove_marriagecertificatedocument_is_recognized"),
    ]

    operations = [
        migrations.AddField(
            model_name="marriagecertificatedocument",
            name="groom_nationality",
            field=models.CharField(default="Malagasy", max_length=100),
        ),
    ]
