# Generated by Django 5.1.1 on 2025-10-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0014_certificatedocument_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificate",
            name="certificate_type",
            field=models.CharField(
                choices=[("F", "Fatherless"), ("N", "Normal"), ("R", "Recognition")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="certificatedocument",
            name="document_number",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="certificatedocument",
            name="document_type",
            field=models.CharField(
                choices=[("F", "Fatherless"), ("N", "Normal"), ("R", "Recognition")],
                max_length=1,
            ),
        ),
    ]
