# Generated by Django 5.1.1 on 2025-11-04 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0014_remove_deathcertificatedocument_client_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathcertificate",
            name="father",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="death_father",
                to="civil.person",
            ),
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="mother",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="death_mother",
                to="civil.person",
            ),
        ),
    ]
