# Generated by Django 5.1.1 on 2025-11-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0014_marriagecertificatedocument_groom_nationality"),
    ]

    operations = [
        migrations.AddField(
            model_name="marriagecertificatedocument",
            name="bride_nationality",
            field=models.CharField(default="Malagasy", max_length=100),
        ),
    ]
