# Generated by Django 5.1.1 on 2025-11-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0014_birthcertificatedocument_declarer_relationship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="birth_type",
            field=models.CharField(default="R", max_length=1),
            preserve_default=False,
        ),
    ]
