# Generated by Django 5.1.1 on 2025-10-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0015_alter_birthcertificate_certificate_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatedocument",
            name="document_number",
            field=models.CharField(max_length=50),
        ),
    ]
