# Generated by Django 5.1.1 on 2025-11-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0015_birthcertificatedocument_birth_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="declarer_gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="person_gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=1
            ),
            preserve_default=False,
        ),
    ]
