# Generated by Django 5.1.1 on 2025-11-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0015_marriagecertificatedocument_bride_nationality"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="is_married",
        ),
    ]
