# Generated by Django 5.1.1 on 2025-11-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0015_deathcertificate_father_deathcertificate_mother"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathcertificate",
            name="date_register",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="date_register",
            field=models.DateTimeField(null=True),
        ),
    ]
