# Generated by Django 5.1.1 on 2025-11-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0016_remove_person_is_married"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="price",
            field=models.FloatField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="price",
            field=models.FloatField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name="marriagecertificatedocument",
            name="mother_bride_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="marriagecertificatedocument",
            name="mother_bride_birthday",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="marriagecertificatedocument",
            name="mother_bride_carreer",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="marriagecertificatedocument",
            name="mother_groom_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="marriagecertificatedocument",
            name="mother_groom_birthday",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="marriagecertificatedocument",
            name="mother_groom_carreer",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="marriagecertificatedocument",
            name="price",
            field=models.FloatField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name="recognizationcertificatedocument",
            name="price",
            field=models.FloatField(default=1000, null=True),
        ),
    ]
