# Generated by Django 5.1.1 on 2025-11-06 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0016_birthcertificatedocument_declarer_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="certificate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deathdoc_certificate",
                to="civil.deathcertificate",
            ),
        ),
    ]
