# Generated by Django 5.1.1 on 2025-10-21 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0013_remove_role_staff_staff_role"),
        ("civil", "0016_alter_certificatedocument_document_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeathCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("declarer_carreer", models.CharField(max_length=80)),
                (
                    "declarer_address",
                    models.CharField(default="Betsiaka", max_length=100),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "dead_birthcertificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="death_dead",
                        to="civil.birthcertificate",
                    ),
                ),
                (
                    "declarer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="death_declarer",
                        to="civil.person",
                    ),
                ),
                (
                    "fokotany",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="death_fokotany",
                        to="administration.fokotany",
                    ),
                ),
                (
                    "responsible_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="death_responsible_role",
                        to="administration.staff",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "dead_birthcertificate",
                            "declarer",
                            "responsible_staff",
                            "fokotany",
                        ),
                        name="unique_death_certificate",
                    )
                ],
            },
        ),
    ]
