# Generated by Django 5.1.1 on 2025-11-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0016_deathcertificate_date_register_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="document_number",
            field=models.IntegerField(null=True),
        ),
    ]
