# Generated by Django 5.1.1 on 2025-11-06 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0017_alter_deathcertificatedocument_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="death_day",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="death_place",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
