# Generated by Django 5.1.1 on 2025-11-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0017_alter_birthcertificatedocument_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marriagecertificatedocument",
            name="mother_bride_birth_place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="marriagecertificatedocument",
            name="mother_bride_last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="marriagecertificatedocument",
            name="mother_groom_birth_place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="marriagecertificatedocument",
            name="mother_groom_last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
