# Generated by Django 5.1.1 on 2025-11-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0017_deathcertificatedocument_document_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deathcertificate",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
