# Generated by Django 5.1.1 on 2025-10-21 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0017_deathcertificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathcertificate",
            name="dead_day",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
