# Generated by Django 5.1.1 on 2025-11-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "civil",
            "0018_alter_marriagecertificatedocument_mother_bride_birth_place_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="is_original",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="is_original",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marriagecertificatedocument",
            name="is_original",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recognizationcertificatedocument",
            name="is_original",
            field=models.BooleanField(default=False),
        ),
    ]
