# Generated by Django 5.1.1 on 2025-11-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0018_alter_deathcertificate_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="birthcertificatedocument",
            name="document_number",
        ),
        migrations.RemoveField(
            model_name="deathcertificatedocument",
            name="document_number",
        ),
    ]
