# Generated by Django 5.1.1 on 2025-11-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0018_deathcertificatedocument_death_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="father_is_alive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="deathcertificatedocument",
            name="mother_is_alive",
            field=models.BooleanField(default=True),
        ),
    ]
