# Generated by Django 5.1.1 on 2025-10-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0018_deathcertificate_dead_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_married",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="birthcertificate",
            name="certificate_type",
            field=models.CharField(
                choices=[("N", "Birth"), ("R", "Birth and Recognition")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="certificatedocument",
            name="document_type",
            field=models.CharField(
                choices=[("N", "Birth"), ("R", "Birth and Recognition")], max_length=1
            ),
        ),
    ]
