# Generated by Django 5.1.1 on 2025-12-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0019_birthcertificatedocument_is_original_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="marriagecertificatedocument",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="recognizationcertificatedocument",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
