# Generated by Django 5.1.1 on 2025-11-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0019_deathcertificatedocument_father_is_alive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="father_is_alive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="mother_is_alive",
            field=models.BooleanField(default=True),
        ),
    ]
