# Generated by Django 5.1.1 on 2025-10-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0019_person_is_married_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="is_married",
        ),
    ]
