# Generated by Django 5.1.1 on 2025-10-22 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0013_remove_role_staff_staff_role"),
        ("civil", "0020_remove_person_is_married"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarriageCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wedding_day", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "bride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="marriage_wife",
                        to="civil.person",
                    ),
                ),
                (
                    "fokotany",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="marriage_fokotany",
                        to="administration.fokotany",
                    ),
                ),
                (
                    "groom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="marriage_husband",
                        to="civil.person",
                    ),
                ),
                (
                    "responsible_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="marriage_responsible_staff",
                        to="administration.staff",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("groom", "bride", "wedding_day"),
                        name="unique_marriage_certificate",
                    )
                ],
            },
        ),
    ]
