# Generated by Django 5.1.1 on 2025-11-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0020_birthcertificatedocument_father_is_alive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="declarer_first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="father_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="father_birth_place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="father_carreer",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="father_first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="father_last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="mother_first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="person_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="person_first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="declarer_first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="father_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="father_birth_place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="father_birthday",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="father_carreer",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="father_first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="father_last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="mother_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="mother_birth_place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="mother_carreer",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="mother_first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="mother_last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="person_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="person_carreer",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="person_first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
