# Generated by Django 5.1.1 on 2025-10-22 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0021_marriagecertificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificate",
            name="date_register",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="date_register",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marriagecertificate",
            name="date_register",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
