# Generated by Django 5.1.1 on 2025-11-08 04:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0021_alter_birthcertificatedocument_declarer_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
