# Generated by Django 5.1.1 on 2025-11-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0022_person_date_created_person_date_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="birthday",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
