# Generated by Django 5.1.1 on 2025-10-23 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0022_birthcertificate_date_register_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthcertificate",
            name="date_declaration",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="declarer_relationship",
            field=models.CharField(default="namana", max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="declarer_was_present",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
