# Generated by Django 5.1.1 on 2025-10-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0023_birthcertificate_date_declaration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificate",
            name="date_register",
            field=models.DateTimeField(null=True),
        ),
    ]
