# Generated by Django 5.1.1 on 2025-11-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0023_alter_person_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deathcertificatedocument",
            name="person_birthday",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
