# Generated by Django 5.1.1 on 2025-10-24 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0013_remove_role_staff_staff_role"),
        ("civil", "0024_alter_birthcertificate_date_register"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deathcertificate",
            name="unique_death_certificate",
        ),
        migrations.RenameField(
            model_name="deathcertificate",
            old_name="dead_day",
            new_name="death_day",
        ),
        migrations.RemoveField(
            model_name="deathcertificate",
            name="dead_birthcertificate",
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="date_declaration",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="dead",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="death_dead",
                to="civil.person",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="dead_address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="dead_carreer",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="death_place",
            field=models.CharField(default="Betsiaka", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="declarer_relationship",
            field=models.CharField(default="namana", max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="father_full_name",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="father_is_alive",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="mother_full_name",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="mother_is_alive",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_alive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="deathcertificate",
            constraint=models.UniqueConstraint(
                fields=("dead", "declarer", "responsible_staff", "fokotany"),
                name="unique_death_certificate",
            ),
        ),
    ]
