# Generated by Django 5.1.1 on 2025-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0024_alter_deathcertificatedocument_person_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="nationality",
            field=models.CharField(
                blank=True, default="malagasy", max_length=100, null=True
            ),
        ),
    ]
