# Generated by Django 5.1.1 on 2025-10-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0025_remove_deathcertificate_unique_death_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="is_alive",
            field=models.BooleanField(default=False),
        ),
    ]
