# Generated by Django 5.1.1 on 2025-10-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0026_alter_person_is_alive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deathcertificate",
            name="date_register",
            field=models.DateTimeField(null=True),
        ),
    ]
