# Generated by Django 5.1.1 on 2025-10-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0027_alter_deathcertificate_date_register"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathcertificate",
            name="declarer_was_present",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
