# Generated by Django 5.1.1 on 2025-10-25 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0028_deathcertificate_declarer_was_present"),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthCertificateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("father_carreer", models.CharField(max_length=80, null=True)),
                ("father_address", models.CharField(max_length=100, null=True)),
                ("mother_carreer", models.CharField(max_length=80)),
                (
                    "mother_address",
                    models.CharField(default="Betsiaka", max_length=100),
                ),
                ("declarer_carreer", models.CharField(max_length=80)),
                (
                    "declarer_address",
                    models.CharField(default="Betsiaka", max_length=100),
                ),
                ("was_alive", models.BooleanField(default=True)),
                ("date_register", models.DateTimeField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("document_number", models.CharField(max_length=50)),
                (
                    "document_type",
                    models.CharField(
                        choices=[("N", "Birth"), ("R", "Birth and Recognition")],
                        max_length=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("VALIDATED", "Validated"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("validated_by", models.CharField(blank=True, max_length=200)),
                (
                    "signature",
                    models.TextField(
                        blank=True, help_text="Digital signature or stamp info"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("price", models.FloatField(default=1000)),
                (
                    "birth_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="civil.birthcertificate",
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_birth_father",
                        to="civil.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Document",
                "verbose_name_plural": "Certificate Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="CertificateDocument",
        ),
    ]
