# Generated by Django 5.1.1 on 2025-10-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0029_birthcertificatedocument_delete_certificatedocument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deathcertificate",
            name="date_register",
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="date_register",
            field=models.DateTimeField(),
        ),
    ]
