# Generated by Django 5.1.1 on 2025-10-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0030_remove_deathcertificate_date_register_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="declarer_address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="mother_address",
            field=models.CharField(max_length=100),
        ),
    ]
