# Generated by Django 5.1.1 on 2025-10-25 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0031_alter_birthcertificatedocument_declarer_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="birth_certificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_birth",
                to="civil.birthcertificate",
            ),
        ),
    ]
