# Generated by Django 5.1.1 on 2025-10-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0032_alter_birthcertificatedocument_birth_certificate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="birthcertificatedocument",
            options={},
        ),
        migrations.RenameField(
            model_name="birthcertificatedocument",
            old_name="validated_at",
            new_name="date_validated",
        ),
        migrations.RemoveField(
            model_name="birthcertificatedocument",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="birthcertificatedocument",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="birthcertificatedocument",
            name="signature",
        ),
        migrations.RemoveField(
            model_name="birthcertificatedocument",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="birthcertificatedocument",
            name="validated_by",
        ),
        migrations.AddField(
            model_name="birthcertificatedocument",
            name="num_copy",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="status",
            field=models.CharField(
                choices=[("D", "Draft"), ("V", "Validated"), ("C", "Cancelled")],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
