# Generated by Django 5.1.1 on 2025-10-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0033_alter_birthcertificatedocument_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="document_number",
            field=models.IntegerField(),
        ),
    ]
