# Generated by Django 5.1.1 on 2025-10-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil", "0034_alter_birthcertificatedocument_document_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="date_register",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="birthcertificatedocument",
            name="document_number",
            field=models.IntegerField(null=True),
        ),
    ]
